Removed gatsby

diff --git a/.github/workflows/deploy_site.yml b/.github/workflows/deploy_site.yml
--- a/.github/workflows/deploy_site.yml
+++ b/.github/workflows/deploy_site.yml
@@ -1,8 +1,8 @@
-# Sample workflow for building and deploying a Gatsby site to GitHub Pages
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
 #
-# To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
 #
-name: Deploy Gatsby site to Pages
+name: Deploy Next.js site to Pages
 
 on:
   # Runs on pushes targeting the default branch
@@ -24,64 +24,66 @@ concurrency:
   group: "pages"
   cancel-in-progress: false
 
-# Default to bash
-defaults:
-  run:
-    shell: bash
-
 jobs:
   # Build job
   build:
     runs-on: ubuntu-latest
-    environment: release_env
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          echo "manager=npm" >> $GITHUB_OUTPUT
-          echo "command=ci" >> $GITHUB_OUTPUT
-          exit 0
-
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
-
       - name: Setup Pages
-        id: pages
-        uses: actions/configure-pages@v5
+        uses: actions/configure-pages@v3
         with:
-          # Automatically inject pathPrefix in your Gatsby configuration file.
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
           #
           # You may remove this line if you want to manage the configuration yourself.
-          static_site_generator: gatsby
+          static_site_generator: next
       - name: Restore cache
         uses: actions/cache@v4
         with:
           path: |
-            site
-            .cache
-          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('site') }}
+            ./site_next/.next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
           restore-keys: |
-            ${{ runner.os }}-gatsby-build-
-
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+     
       - name: Install dependencies
-        working-directory: ./site
+        working-directory: ./site_next
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-
-      - name: Build with Gatsby
-        working-directory: ./site
-        env:
-          PREFIX_PATHS: 'true'
-        run: ${{ steps.detect-package-manager.outputs.manager }} run build
+     
+      - name: Build with Next.js
+        working-directory: ./site_next
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./site/public
+          path: ./site_next/out
 
   # Deployment job
   deploy:
